# Generated by Django 2.0.6 on 2019-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('charge1', models.IntegerField(default=0)),
                ('charge2', models.IntegerField(default=0)),
            ],
        ),
    ]
